[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "disco_rl"
version = "2.0.0"
description = "DiscoRL: PyTorch CUDA 12.9 reinforcement-learning implementation."
readme = "README.md"
requires-python = ">=3.11,<3.13"
license-files = ["LICENSE"]
authors = [{name = "DiscoRL team", email="disco_rl@google.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
]
keywords = [
  "reinforcement learning",
  "rl",
  "pytorch",
  "cuda",
  "cuda 12.9",
  "actor critic",
]
dependencies = [
  "numpy>=1.26",
  "torch>=2.9.0.dev",
]

[project.urls]
repository = "https://github.com/google-deepmind/disco_rl"

[tool.setuptools.packages.find]
where = ["."]
include = ["disco_rl*"]
