[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "disco_rl"
version = "1.0.0"
description = "DiscoRL: PyTorch/CUDA 12.9 implementation of discovered reinforcement-learning update rules."
readme = "README.md"
requires-python = ">=3.11"
license-files = ["LICENSE"]
authors = [{name = "DiscoRL team", email="disco_rl@google.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
]
keywords = [
  "reinforcement learning",
  "rl",
  "meta learning",
  "meta",
  "update rule",
  "automated discovery",
  "automl",
  "algorithm discovery",
  "data driven research",
]

dependencies = [
  "torch==2.8.0",
  "numpy>=1.26",
  "dm-env>=1.6",
  "ml-collections>=0.1.1",
  "matplotlib>=3.8",
  "seaborn>=0.13",
  "pandas>=2.2",
  "tqdm>=4.66",
  "ipykernel>=6.29",
  "notebook>=7.2",
]

[project.optional-dependencies]
cuda129 = [
  "torch==2.8.0",
]

[project.urls]
repository = "https://github.com/google-deepmind/disco_rl"

[tool.setuptools.packages.find]
where = ["."]
include = ["disco_rl*"]
