"""Environment protocol aliases."""
from __future__ import annotations
from typing import Protocol, Any
class Environment(Protocol):
  def reset(self, *args, **kwargs) -> Any: ...
  def step(self, *args, **kwargs) -> Any: ...
